name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download artifact from Traktor
      uses: benday-inc/download-latest-artifact@main
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository_owner: apistol78
         repository_name: traktor
         workflow_name: 'Build Windows'
         branch_name: 'master'
         artifact_name: 'traktor'
         download_path: '${{ github.workspace }}/temp'
         download_filename: 'traktor.zip'
    #- run: dir ${{ github.workspace }}/temp
    - name: Extract Traktor
      run: powershell Expand-Archive ${{ github.workspace }}/temp/traktor.zip -DestinationPath ${{ github.workspace }}/traktor 
    #- run: dir ${{ github.workspace }}/traktor
    - name: Install Blender
      uses: moguri/setup-blender@v1
      with:
        blender-version: '4.0'
    #- run: blender --version    
    - name: Build
      run: ./scripts/autobuild-win64.bat
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: Archive
        path: |
          output/Kartong/Windows/bin64/
          output/Kartong/Windows/Application.config
          output/Kartong/Windows/Content.compact
          scripts/launch.bat
